
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL
      - OPENROUTER_API_KEY
      - MODEL_NAME
      - OPENROUTER_API_URL
      - API_BASE_URL
      - ENVIRONMENT
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    restart: unless-stopped

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ai_crud
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

 
volumes:
  postgres_data: