FROM python:latest

WORKDIR /app

# 安装系统依赖
RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    libglib2.0-0 \
    libnss3 \
    libgconf-2-4 \
    libfontconfig1 \
    && rm -rf /var/lib/apt/lists/*

# 复制测试依赖文件
COPY tests/requirements-test.txt /app/tests/requirements-test.txt

# 安装测试依赖
RUN pip install -r /app/tests/requirements-test.txt

# 设置Python路径
ENV PYTHONPATH=/app 